### ISSUE TITLE
Failure to install on RPi 4B

### ISSUE THREAD

**Issue by dchamb55** [kennethjiang/OctoPrint-Anywhere#113]
When I try to install the plugin, this is what is displayed:

Installing plugin "OctoPrint Anywhere" from https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpt7AkID/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpt7AkID/master.zip
Requirement already satisfied: OctoPrint>=1.2.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Anywhere==1.1.1) (1.5.3)
Requirement already satisfied: backoff>=1.4.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Anywhere==1.1.1) (1.10.0)
Requirement already satisfied: raven in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Anywhere==1.1.1) (6.10.0)
Collecting picamera==1.13
Downloading https://files.pythonhosted.org/packages/79/c4/80afe871d82ab1d5c9d8f0c0258228a8a0ed96db07a78ef17e7fba12fda8/picamera-1.13.tar.gz (143kB)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.0.0)
Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.10.4)
Requirement already satisfied: OctoPrint-FileCheck>=2020.08.07 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2020.8.7)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (5.8.0)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.5.4)
Requirement already satisfied: monotonic<2,>=1.5; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.5)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.0.7)
Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (5.4.1)
Requirement already satisfied: feedparser<6,>=5.2.1; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (5.2.1)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.10.9)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.18.2)
Requirement already satisfied: enum34<1.2,>=1.1.10; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.1.10)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.7.19)
Requirement already satisfied: requests<3,>=2.23.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.25.1)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (7.1.2)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.1.0)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.4)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.11.2)
Requirement already satisfied: frozendict<2,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.2)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.5.0)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.1.2)
Requirement already satisfied: rsa==4.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (4.0)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.8.5)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.4.21)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.5.0.1)
Requirement already satisfied: futures<4,>=3.3; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.3.0)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.57.0)
Requirement already satisfied: scandir<2,>=1.10; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.10.0)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (5.1.1)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.4)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.1.1)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.1.1)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2019.8.19)
Requirement already satisfied: chainmap<2,>=1.0.3; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.0.3)
Requirement already satisfied: typing<4,>=3.7.4.1; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.7.4.1)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.1.5.post0)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.09.23 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2020.9.23)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.19.5)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.2.0)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.0.1)
Requirement already satisfied: wrapt<2,>=1.12.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.12.1)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.0)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.1)
Requirement already satisfied: contextlib2; python_version < "3.2" in /home/pi/oprint/lib/python2.7/site-packages (from raven->OctoPrint-Anywhere==1.1.1) (0.6.0.post1)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.7.0)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2019.3)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from watchdog==0.10.4->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.1.2)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2019.9.11)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.0.4)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages (from rsa==4.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.4.7)
Requirement already satisfied: six in /home/pi/oprint/lib/python2.7/site-packages (from websocket-client<1,>=0.57->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (1.12.0)
Requirement already satisfied: backports-abc>=0.4 in /home/pi/oprint/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (0.5)
Requirement already satisfied: singledispatch in /home/pi/oprint/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (3.4.0.3)
Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python2.7/site-packages (from markdown<3.2,>=3.1->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (41.5.1)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint>=1.2.4->OctoPrint-Anywhere==1.1.1) (2.0)
Building wheels for collected packages: OctoPrint-Anywhere, picamera
Building wheel for OctoPrint-Anywhere (setup.py): started
Building wheel for OctoPrint-Anywhere (setup.py): finished with status 'done'
Created wheel for OctoPrint-Anywhere: filename=OctoPrint_Anywhere-1.1.1-cp27-none-any.whl size=9025843 sha256=270767134d1ffc94820a228a5636190e42d258899ef031442b4501304bcb830c
Stored in directory: /tmp/pip-ephem-wheel-cache-mTaVv5/wheels/dd/a0/95/4a317ad84c08533b1f7d5998edfad2aeb6defb0f8f1f21a959
Building wheel for picamera (setup.py): started
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bixqHC --python-tag cp27
cwd: /tmp/pip-install-7UoGL3/picamera/
Complete output (54 lines):
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/picamera
copying picamera/mmalobj.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/array.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/frames.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/camera.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/renderers.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/__init__.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/bcm_host.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/mmal.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/encoders.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/display.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/color.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/streams.py -> build/lib.linux-armv7l-2.7/picamera
copying picamera/exc.py -> build/lib.linux-armv7l-2.7/picamera
running egg_info
writing requirements to picamera.egg-info/requires.txt
writing picamera.egg-info/PKG-INFO
writing top-level names to picamera.egg-info/top_level.txt
writing dependency_links to picamera.egg-info/dependency_links.txt
reading manifest file 'picamera.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'debian'
no previously-included directories found matching 'docs'
writing manifest file 'picamera.egg-info/SOURCES.txt'
installing to build/bdist.linux-armv7l/wheel
running install
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 145, in <module>
main()
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 140, in main
cmdclass             = {'install': CustomInstallCommand},
File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/home/pi/oprint/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 228, in run
self.run_command('install')
File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 109, in run
raise ValueError('This system does not appear to be a Raspberry Pi')
ValueError: This system does not appear to be a Raspberry Pi
----------------------------------------
ERROR: Failed building wheel for picamera
Building wheel for picamera (setup.py): finished with status 'error'
Running setup.py clean for picamera
Successfully built OctoPrint-Anywhere
Failed to build picamera
Installing collected packages: picamera, OctoPrint-Anywhere
Running setup.py install for picamera: started
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lY7CJK/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/picamera
cwd: /tmp/pip-install-7UoGL3/picamera/
Complete output (18 lines):
running install
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 145, in <module>
main()
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 140, in main
cmdclass             = {'install': CustomInstallCommand},
File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/tmp/pip-install-7UoGL3/picamera/setup.py", line 109, in run
raise ValueError('This system does not appear to be a Raspberry Pi')
ValueError: This system does not appear to be a Raspberry Pi
----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/oprint/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7UoGL3/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lY7CJK/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/oprint/include/site/python2.7/picamera Check the logs for full command output.
Running setup.py install for picamera: finished with status 'error'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by kennethjiang** [comment]
Are you using OctoPi 0.18 RC 64-bit build? If so, it's known to have issues.

**Comment by dchamb55** [comment]
I am using the following:

OctoPrint 1.5.3 Python 2.7.16 OctoPi 0.17.0 on a Raspberry Pi 4 Model B Rev 1.1


I get notices to upgrade to OctoPi 0.18.0 but have avoided applying the update.


Any suggestions?


Regards


Dale




Dale A. Chamberlain
15210 Humbert Rd
Brighton, IL 62012-1955


Ph. (314) 218-0557
Email: dale@dchamberlain.net

**Comment by dchamb55** [comment]
I am using Octopi 0.17.0 64-bit

**Comment by kennethjiang** [comment]
Sorry for whatever reason your comments fell through the cracks in my inbox.

I'm pretty sure this is caused by the stability issues with OctoPi 0.18 RC builds. Now OctoPi 0.18 stable build is released. Please re-flash your SD card with the stable build image from https://octoprint.org/download/. Let me know if you still have issues.

**Comment by dchamb55** [comment]
I could understand that if I was running Octopi 0.18 but I have never installed it or any RC builds of it. I am running 0.17.

**Comment by kennethjiang** [comment]
@dchamb55 I'm under the impression that only 0.18 RC has a 64-bit. 0.17 never did. But I could be wrong.
